/* Micro Controlled Fun - application logic. Data lives under /data. */
const state={boardId:"",inventory:new Map(),category:"all",recipes:[],boards:[],components:[]};
const boardSelect=document.getElementById("boardSelect"),componentList=document.getElementById("componentList"),hardwareMessage=document.getElementById("hardwareMessage"),findProjectsButton=document.getElementById("findProjects"),projectGrid=document.getElementById("projectGrid"),noProjects=document.getElementById("noProjects"),filterButtons=document.querySelectorAll(".filter"),builderArea=document.getElementById("builderArea"),startBuilding=document.getElementById("startBuilding"),browseProjects=document.getElementById("browseProjects");
async function loadJson(path){const r=await fetch(path,{cache:"no-store"});if(!r.ok)throw new Error(`Could not load ${path}`);return r.json()}
async function init(){try{[state.recipes,state.boards,state.components]=await Promise.all([loadJson("data/recipes/index.json"),loadJson("data/boards/index.json"),loadJson("data/components/index.json")]);renderBoards();renderComponents();renderProjects();setupEvents();updateHardwareMessage()}catch(e){projectGrid.innerHTML=`<div class="no-projects"><div><strong>Couldn't load the project data.</strong><p>${escapeHtml(e.message)}</p></div></div>`}}
function renderBoards(){boardSelect.innerHTML=`<option value="">Select your board</option>`+state.boards.map(b=>`<option value="${escapeHtml(b.id)}">${escapeHtml(b.name)}</option>`).join("")}
function renderComponents(){componentList.innerHTML=state.components.filter(c=>c.category!=="wiring").map(c=>`<button class="component" type="button" data-component="${escapeHtml(c.id)}">${escapeHtml(c.name)}</button>`).join("");componentList.querySelectorAll(".component").forEach(btn=>btn.addEventListener("click",()=>{const id=btn.dataset.component;if(state.inventory.has(id)){state.inventory.delete(id);btn.classList.remove("selected")}else{state.inventory.set(id,1);btn.classList.add("selected")}updateHardwareMessage()}))}
function setupEvents(){boardSelect.addEventListener("change",()=>{state.boardId=boardSelect.value;updateHardwareMessage()});findProjectsButton.addEventListener("click",()=>{renderProjects();document.getElementById("projects").scrollIntoView({behavior:"smooth"})});filterButtons.forEach(btn=>btn.addEventListener("click",()=>{filterButtons.forEach(x=>x.classList.remove("active"));btn.classList.add("active");state.category=btn.dataset.category;renderProjects()}));startBuilding.addEventListener("click",()=>document.getElementById("hardware").scrollIntoView({behavior:"smooth"}));browseProjects.addEventListener("click",()=>document.getElementById("projects").scrollIntoView({behavior:"smooth"}))}
function updateHardwareMessage(){const board=state.boards.find(b=>b.id===state.boardId),count=[...state.inventory.values()].reduce((a,b)=>a+b,0);hardwareMessage.textContent=!board&&!count?"Choose a board and some components to get started.":`${board?board.name:"Any board"} · ${count} selected part${count===1?"":"s"}`}
function getMatchingRecipes(){return state.recipes.filter(r=>{if(state.category!=="all"&&r.category!==state.category)return false;if(state.boardId&&!r.supportedBoards.includes(state.boardId))return false;for(const [id,q]of state.inventory.entries()){const req=r.requiredHardware.find(x=>x.id===id);if(!req||q<req.quantity)return false}return true})}
function renderProjects(){const matches=getMatchingRecipes();noProjects.classList.toggle("hidden",matches.length!==0);projectGrid.innerHTML=matches.map(r=>`<article class="project-card" data-project="${escapeHtml(r.id)}"><div class="project-category">${escapeHtml(r.category)} · ${escapeHtml(r.difficulty)}</div><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.description)}</p><div class="project-bottom">${r.requiredHardware.slice(0,5).map(x=>`<span class="project-tag">${formatQuantity(x.quantity)} ${escapeHtml(getHardwareName(x.id))}</span>`).join("")}</div></article>`).join("");projectGrid.querySelectorAll(".project-card").forEach(c=>c.addEventListener("click",()=>openRecipe(c.dataset.project)))}
function openRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;builderArea.innerHTML=`<div class="builder-content"><div class="eyebrow">${escapeHtml(r.category)} · ${escapeHtml(r.difficulty)}</div><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.description)}</p><div class="builder-details"><div class="builder-detail"><strong>Supported boards</strong><span>${r.supportedBoards.map(getBoardName).join(", ")}</span></div><div class="builder-detail"><strong>Required hardware</strong><span>${formatRequirements(r.requiredHardware)}</span></div><div class="builder-detail"><strong>Optional hardware</strong><span>${r.optionalHardware?.length?formatRequirements(r.optionalHardware):"None listed"}</span></div><div class="builder-detail"><strong>Your board</strong><span>${escapeHtml(state.boardId?getBoardName(state.boardId):"Choose a board")}</span></div></div><div style="margin-top:24px"><button id="configureProject" class="button button-primary" type="button">Configure connections <span>→</span></button></div></div>`;document.getElementById("configureProject").addEventListener("click",()=>openPinMapper(r));document.getElementById("builder").scrollIntoView({behavior:"smooth"})}
function openPinMapper(r){const b=state.boards.find(x=>x.id===state.boardId);if(!b){builderArea.innerHTML=`<div class="builder-empty"><div><strong>Choose your board first.</strong><p>Select the board you're actually using before wiring the project.</p></div></div>`;return}if(!b.pins?.length){builderArea.innerHTML=`<div class="builder-empty"><div><strong>This board needs its exact board definition first.</strong><p>We won't invent pin mappings. The project can be published now, but configuration waits for its board adapter.</p></div></div>`;return}const rows=r.connections.map(c=>`<div class="builder-detail"><strong>${escapeHtml(c.label)}</strong><span>${escapeHtml(c.signal)} <select class="pin-choice" data-connection="${escapeHtml(c.id)}"><option value="">Choose pin</option>${b.pins.map(p=>`<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`).join("")}</select></span></div>`).join("");builderArea.innerHTML=`<div class="builder-content"><div class="eyebrow">CONNECTION SETUP</div><h3>${escapeHtml(r.title)}</h3><p>Pick a physical pin for each connection. This configuration will later feed the firmware template.</p><div class="builder-details">${rows}</div><div style="margin-top:24px"><button id="savePins" class="button button-primary" type="button">Save connections <span>→</span></button></div></div>`;document.getElementById("savePins").addEventListener("click",()=>{const map={};let ok=true;document.querySelectorAll(".pin-choice").forEach(s=>{map[s.dataset.connection]=s.value;if(!s.value)ok=false});if(!ok){alert("Choose a pin for every connection.");return}builderArea.innerHTML=`<div class="builder-content"><div class="eyebrow">CONNECTIONS SAVED</div><h3>${escapeHtml(r.title)}</h3><p>Your wiring choices are saved for this session.</p><div class="builder-details">${r.connections.map(c=>`<div class="builder-detail"><strong>${escapeHtml(c.label)}</strong><span>${escapeHtml(map[c.id])}</span></div>`).join("")}</div><p>Board: ${escapeHtml(b.name)}</p></div>`})}
function formatRequirements(items){return items.map(x=>`${formatQuantity(x.quantity)} ${getHardwareName(x.id)}`).join(", ")}
function formatQuantity(q){return q===1?"1×":`${q}×`}
function getHardwareName(id){return state.components.find(c=>c.id===id)?.name||id}
function getBoardName(id){return state.boards.find(b=>b.id===id)?.name||id}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
init();
